### ISSUE TITLE
Block device incorrectly detected as mtd device

### ISSUE THREAD

**Issue by andersm** [sbabic/libubootenv#11]
On my device, I have been using the block device /dev/mtdblock4 to access the environment. With the old U-Boot fw_setenv this worked fine, but libubootenv incorrectly detects this as an MTD device, causing writes to fail.

**Comment by sbabic** [comment]
Please see the contributing page, Github issues are not used for this project.
mtdblock devices are usually for filesystems - raw access is done via /dev/mtd devices. libubootenv does not consider block devices as MTD, confirmed this is a difference with old u-u-boot-fw-utils.
