### ISSUE TITLE
fw_printenv 'undefined symbol: crc32'

### ISSUE THREAD

**Issue by mmader87** [sbabic/libubootenv#6]
Hello,
Attempting to use fw_printenv on raspberry pi cm3.  However, this always comes back with the error:
fw_printenv: symbol lookup error: /usr/lib/libubootenv.so.0.1: undefined symbol: crc32

Attempted to link with zlib but still no luck.  Any thoughts?

Thank you for your time.

**Comment by sbabic** [comment]
Hi,

not stated in doc, but the ML for libubootenv is the same as for 
SWUpdate - I do not use github issues. Just mail to :

	swupdate@googlegroups.com

On 15.06.20 22:33, mmader87 wrote:
> Hello,
> Attempting to use fw_printenv on raspberry pi cm3. However, this always 
> comes back with the error:
> fw_printenv: symbol lookup error: /usr/lib/libubootenv.so.0.1: undefined 
> symbol: crc32
> 

crc32 is defined in libz, if you still get the error, libz is not 
linked. Which OE version are you using ? I do not see problems with dunfell.


> Attempted to link with zlib but still no luck. Any thoughts?
> 
> Thank you for your time.
> 

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by mmader87** [comment]
Thank you for the reply.  I posted the question to the googlegroups you mentioned.

Just for reference, I am using warrior.
