### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bgermann** [sbabic/libubootenv#9]
How about a 0.3 release? Especially the pkgconfig support would be nice to have in a release.

**Comment by sbabic** [comment]
Hi Bastian,

On 11.08.20 11:20, bgermann wrote:
> How about a 0.3 release? Especially the pkgconfig support would be nice
> to have in a release.

Yes, I thought the same ;-).

Really I thought to push a new release before next poky (so OE), but I
guess this does not help other build system (I assume you have Debian /
Elbe).

I will tag a 0.3 soon.

Best regards,
Stefano


-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================
